// Mocks generated by Mockito 5.4.6 from annotations
// in vidyut/test/seller_page_comprehensive_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:vidyut/app/app_state.dart' as _i7;
import 'package:vidyut/features/sell/models.dart' as _i3;
import 'package:vidyut/features/sell/store/seller_store.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SellerStore].
///
/// See the documentation for Mockito's code generation for more information.
class MockSellerStore extends _i1.Mock implements _i2.SellerStore {
  MockSellerStore() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Product> get products => (super.noSuchMethod(
        Invocation.getter(#products),
        returnValue: <_i3.Product>[],
      ) as List<_i3.Product>);

  @override
  List<_i3.CustomFieldDef> get profileFields => (super.noSuchMethod(
        Invocation.getter(#profileFields),
        returnValue: <_i3.CustomFieldDef>[],
      ) as List<_i3.CustomFieldDef>);

  @override
  List<_i3.Lead> get leads => (super.noSuchMethod(
        Invocation.getter(#leads),
        returnValue: <_i3.Lead>[],
      ) as List<_i3.Lead>);

  @override
  String get bannerUrl => (super.noSuchMethod(
        Invocation.getter(#bannerUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#bannerUrl),
        ),
      ) as String);

  @override
  List<String> get profileMaterials => (super.noSuchMethod(
        Invocation.getter(#profileMaterials),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<_i3.AdCampaign> get ads => (super.noSuchMethod(
        Invocation.getter(#ads),
        returnValue: <_i3.AdCampaign>[],
      ) as List<_i3.AdCampaign>);

  @override
  String get primaryPhone => (super.noSuchMethod(
        Invocation.getter(#primaryPhone),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#primaryPhone),
        ),
      ) as String);

  @override
  String get primaryEmail => (super.noSuchMethod(
        Invocation.getter(#primaryEmail),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#primaryEmail),
        ),
      ) as String);

  @override
  String get website => (super.noSuchMethod(
        Invocation.getter(#website),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#website),
        ),
      ) as String);

  @override
  List<String> get additionalPhones => (super.noSuchMethod(
        Invocation.getter(#additionalPhones),
        returnValue: <String>[],
      ) as List<String>);

  @override
  List<String> get additionalEmails => (super.noSuchMethod(
        Invocation.getter(#additionalEmails),
        returnValue: <String>[],
      ) as List<String>);

  @override
  int get profileViews => (super.noSuchMethod(
        Invocation.getter(#profileViews),
        returnValue: 0,
      ) as int);

  @override
  int get sellerContactCalls => (super.noSuchMethod(
        Invocation.getter(#sellerContactCalls),
        returnValue: 0,
      ) as int);

  @override
  int get sellerContactWhatsapps => (super.noSuchMethod(
        Invocation.getter(#sellerContactWhatsapps),
        returnValue: 0,
      ) as int);

  @override
  int get totalSellerContacts => (super.noSuchMethod(
        Invocation.getter(#totalSellerContacts),
        returnValue: 0,
      ) as int);

  @override
  String get currentPlan => (super.noSuchMethod(
        Invocation.getter(#currentPlan),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#currentPlan),
        ),
      ) as String);

  @override
  bool get isFreePlan => (super.noSuchMethod(
        Invocation.getter(#isFreePlan),
        returnValue: false,
      ) as bool);

  @override
  bool get isPlusPlan => (super.noSuchMethod(
        Invocation.getter(#isPlusPlan),
        returnValue: false,
      ) as bool);

  @override
  bool get isProPlan => (super.noSuchMethod(
        Invocation.getter(#isProPlan),
        returnValue: false,
      ) as bool);

  @override
  int get maxProducts => (super.noSuchMethod(
        Invocation.getter(#maxProducts),
        returnValue: 0,
      ) as int);

  @override
  int get maxAds => (super.noSuchMethod(
        Invocation.getter(#maxAds),
        returnValue: 0,
      ) as int);

  @override
  bool get hasAnalytics => (super.noSuchMethod(
        Invocation.getter(#hasAnalytics),
        returnValue: false,
      ) as bool);

  @override
  bool get hasAdvancedFeatures => (super.noSuchMethod(
        Invocation.getter(#hasAdvancedFeatures),
        returnValue: false,
      ) as bool);

  @override
  int get totalProductViews => (super.noSuchMethod(
        Invocation.getter(#totalProductViews),
        returnValue: 0,
      ) as int);

  @override
  int get totalProductContacts => (super.noSuchMethod(
        Invocation.getter(#totalProductContacts),
        returnValue: 0,
      ) as int);

  @override
  List<_i3.Product> get topViewedProducts => (super.noSuchMethod(
        Invocation.getter(#topViewedProducts),
        returnValue: <_i3.Product>[],
      ) as List<_i3.Product>);

  @override
  Map<String, dynamic> get profileData => (super.noSuchMethod(
        Invocation.getter(#profileData),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  List<_i3.Lead> get allLeads => (super.noSuchMethod(
        Invocation.getter(#allLeads),
        returnValue: <_i3.Lead>[],
      ) as List<_i3.Lead>);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  int productViewsOf(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #productViewsOf,
          [productId],
        ),
        returnValue: 0,
      ) as int);

  @override
  int productContactCallsOf(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #productContactCallsOf,
          [productId],
        ),
        returnValue: 0,
      ) as int);

  @override
  int productContactWhatsappsOf(String? productId) => (super.noSuchMethod(
        Invocation.method(
          #productContactWhatsappsOf,
          [productId],
        ),
        returnValue: 0,
      ) as int);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setBannerUrl(String? url) => super.noSuchMethod(
        Invocation.method(
          #setBannerUrl,
          [url],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setProfileMaterials(List<String>? materials) => super.noSuchMethod(
        Invocation.method(
          #setProfileMaterials,
          [materials],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPrimaryPhone(String? phone) => super.noSuchMethod(
        Invocation.method(
          #setPrimaryPhone,
          [phone],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPrimaryEmail(String? email) => super.noSuchMethod(
        Invocation.method(
          #setPrimaryEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setWebsite(String? website) => super.noSuchMethod(
        Invocation.method(
          #setWebsite,
          [website],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAdditionalPhones(List<String>? phones) => super.noSuchMethod(
        Invocation.method(
          #setAdditionalPhones,
          [phones],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAdditionalEmails(List<String>? emails) => super.noSuchMethod(
        Invocation.method(
          #setAdditionalEmails,
          [emails],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void upsertAd(_i3.AdCampaign? ad) => super.noSuchMethod(
        Invocation.method(
          #upsertAd,
          [ad],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteAd(String? id) => super.noSuchMethod(
        Invocation.method(
          #deleteAd,
          [id],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void incrementProfileView() => super.noSuchMethod(
        Invocation.method(
          #incrementProfileView,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordSellerContactCall() => super.noSuchMethod(
        Invocation.method(
          #recordSellerContactCall,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordSellerContactWhatsapp() => super.noSuchMethod(
        Invocation.method(
          #recordSellerContactWhatsapp,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordProductView(String? productId) => super.noSuchMethod(
        Invocation.method(
          #recordProductView,
          [productId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordProductContactCall(String? productId) => super.noSuchMethod(
        Invocation.method(
          #recordProductContactCall,
          [productId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordProductContactWhatsapp(String? productId) => super.noSuchMethod(
        Invocation.method(
          #recordProductContactWhatsapp,
          [productId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addProduct(_i3.Product? product) => super.noSuchMethod(
        Invocation.method(
          #addProduct,
          [product],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateProduct(_i3.Product? product) => super.noSuchMethod(
        Invocation.method(
          #updateProduct,
          [product],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteProduct(String? productId) => super.noSuchMethod(
        Invocation.method(
          #deleteProduct,
          [productId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Product? getProduct(String? productId) =>
      (super.noSuchMethod(Invocation.method(
        #getProduct,
        [productId],
      )) as _i3.Product?);

  @override
  void addProfileField(_i3.CustomFieldDef? field) => super.noSuchMethod(
        Invocation.method(
          #addProfileField,
          [field],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateProfileField(_i3.CustomFieldDef? field) => super.noSuchMethod(
        Invocation.method(
          #updateProfileField,
          [field],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void deleteProfileField(String? fieldId) => super.noSuchMethod(
        Invocation.method(
          #deleteProfileField,
          [fieldId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> saveProfileData({
    required String? legalName,
    required String? gstin,
    required String? phone,
    required String? email,
    required String? address,
    required String? website,
    String? bannerUrl,
    List<String>? materials,
    List<_i3.CustomFieldDef>? customFields,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveProfileData,
          [],
          {
            #legalName: legalName,
            #gstin: gstin,
            #phone: phone,
            #email: email,
            #address: address,
            #website: website,
            #bannerUrl: bannerUrl,
            #materials: materials,
            #customFields: customFields,
          },
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> loadProfileData() => (super.noSuchMethod(
        Invocation.method(
          #loadProfileData,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  void updateLead(_i3.Lead? lead) => super.noSuchMethod(
        Invocation.method(
          #updateLead,
          [lead],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<void> createLead(_i3.Lead? lead) => (super.noSuchMethod(
        Invocation.method(
          #createLead,
          [lead],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> deleteLead(String? leadId) => (super.noSuchMethod(
        Invocation.method(
          #deleteLead,
          [leadId],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i3.Lead? getLead(String? leadId) => (super.noSuchMethod(Invocation.method(
        #getLead,
        [leadId],
      )) as _i3.Lead?);

  @override
  void recordLeadView(String? leadId) => super.noSuchMethod(
        Invocation.method(
          #recordLeadView,
          [leadId],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void recordLeadContact(
    String? leadId,
    String? contactMethod,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #recordLeadContact,
          [
            leadId,
            contactMethod,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addLead(_i3.Lead? lead) => super.noSuchMethod(
        Invocation.method(
          #addLead,
          [lead],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void updateSubscriptionPlan(String? plan) => super.noSuchMethod(
        Invocation.method(
          #updateSubscriptionPlan,
          [plan],
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool canAddProduct() => (super.noSuchMethod(
        Invocation.method(
          #canAddProduct,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  bool canAddAd() => (super.noSuchMethod(
        Invocation.method(
          #canAddAd,
          [],
        ),
        returnValue: false,
      ) as bool);

  @override
  String getSubscriptionStatus() => (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionStatus,
          [],
        ),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.method(
            #getSubscriptionStatus,
            [],
          ),
        ),
      ) as String);

  @override
  Map<String, dynamic> getSubscriptionLimits() => (super.noSuchMethod(
        Invocation.method(
          #getSubscriptionLimits,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [AppState].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppState extends _i1.Mock implements _i7.AppState {
  MockAppState() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get city => (super.noSuchMethod(
        Invocation.getter(#city),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#city),
        ),
      ) as String);

  @override
  String get area => (super.noSuchMethod(
        Invocation.getter(#area),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#area),
        ),
      ) as String);

  @override
  String get state => (super.noSuchMethod(
        Invocation.getter(#state),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#state),
        ),
      ) as String);

  @override
  double get radiusKm => (super.noSuchMethod(
        Invocation.getter(#radiusKm),
        returnValue: 0.0,
      ) as double);

  @override
  _i7.LocationMode get mode => (super.noSuchMethod(
        Invocation.getter(#mode),
        returnValue: _i7.LocationMode.manual,
      ) as _i7.LocationMode);

  @override
  bool get isAdmin => (super.noSuchMethod(
        Invocation.getter(#isAdmin),
        returnValue: false,
      ) as bool);

  @override
  set city(String? _city) => super.noSuchMethod(
        Invocation.setter(
          #city,
          _city,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set area(String? _area) => super.noSuchMethod(
        Invocation.setter(
          #area,
          _area,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set state(String? _state) => super.noSuchMethod(
        Invocation.setter(
          #state,
          _state,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set radiusKm(double? _radiusKm) => super.noSuchMethod(
        Invocation.setter(
          #radiusKm,
          _radiusKm,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set mode(_i7.LocationMode? _mode) => super.noSuchMethod(
        Invocation.setter(
          #mode,
          _mode,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set latitude(double? _latitude) => super.noSuchMethod(
        Invocation.setter(
          #latitude,
          _latitude,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set longitude(double? _longitude) => super.noSuchMethod(
        Invocation.setter(
          #longitude,
          _longitude,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isAdmin(bool? _isAdmin) => super.noSuchMethod(
        Invocation.setter(
          #isAdmin,
          _isAdmin,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
      ) as bool);

  @override
  void addLocationChangeListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #addLocationChangeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeLocationChangeListener(_i6.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(
          #removeLocationChangeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setLocation({
    required String? city,
    String? area,
    required String? state,
    required double? radiusKm,
    _i7.LocationMode? mode,
    double? latitude,
    double? longitude,
  }) =>
      super.noSuchMethod(
        Invocation.method(
          #setLocation,
          [],
          {
            #city: city,
            #area: area,
            #state: state,
            #radiusKm: radiusKm,
            #mode: mode,
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setCity(String? city) => super.noSuchMethod(
        Invocation.method(
          #setCity,
          [city],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setState(String? state) => super.noSuchMethod(
        Invocation.method(
          #setState,
          [state],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setRadius(double? radiusKm) => super.noSuchMethod(
        Invocation.method(
          #setRadius,
          [radiusKm],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setAdmin(bool? value) => super.noSuchMethod(
        Invocation.method(
          #setAdmin,
          [value],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i6.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
