// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQvQ', // You'll need to get this from Firebase Console
    appId: '1:612881568506:web:YOUR_WEB_APP_ID', // You'll need to get this from Firebase Console
    messagingSenderId: '612881568506',
    projectId: 'vidyut1',
    authDomain: 'vidyut1.firebaseapp.com',
    storageBucket: 'vidyut1.appspot.com',
    measurementId: 'YOUR_MEASUREMENT_ID', // You'll need to get this from Firebase Console
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY', // You'll need to get this from Firebase Console
    appId: '1:612881568506:android:YOUR_ANDROID_APP_ID', // You'll need to get this from Firebase Console
    messagingSenderId: '612881568506',
    projectId: 'vidyut1',
    storageBucket: 'vidyut1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY', // You'll need to get this from Firebase Console
    appId: '1:612881568506:ios:YOUR_IOS_APP_ID', // You'll need to get this from Firebase Console
    messagingSenderId: '612881568506',
    projectId: 'vidyut1',
    storageBucket: 'vidyut1.appspot.com',
    iosBundleId: 'com.example.vidyut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'YOUR_MACOS_API_KEY', // You'll need to get this from Firebase Console
    appId: '1:612881568506:macos:YOUR_MACOS_APP_ID', // You'll need to get this from Firebase Console
    messagingSenderId: '612881568506',
    projectId: 'vidyut1',
    storageBucket: 'vidyut1.appspot.com',
    iosBundleId: 'com.example.vidyut',
  );
}
