// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuFr481cjL2WHsbsMeleXjKUyOAEyoUcg',
    appId: '1:940313957771:web:30b6f131a08a7a808a0b8e',
    messagingSenderId: '940313957771',
    projectId: 'vidyutnidhi5',
    authDomain: 'vidyutnidhi5.firebaseapp.com',
    storageBucket: 'vidyutnidhi5.firebasestorage.app',
    measurementId: 'G-0YXWN8HV32',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6Lu3_M9dsnd69nNZiXAB_7OczcerYe34',
    appId: '1:940313957771:android:2b9f790bff58a4fe8a0b8e',
    messagingSenderId: '940313957771',
    projectId: 'vidyutnidhi5',
    storageBucket: 'vidyutnidhi5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFr481cjL2WHsbsMeleXjKUyOAEyoUcg',
    appId: '1:940313957771:ios:your-ios-app-id',
    messagingSenderId: '940313957771',
    projectId: 'vidyutnidhi5',
    storageBucket: 'vidyutnidhi5.firebasestorage.app',
    iosBundleId: 'com.example.vidyut',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFr481cjL2WHsbsMeleXjKUyOAEyoUcg',
    appId: '1:940313957771:ios:your-macos-app-id',
    messagingSenderId: '940313957771',
    projectId: 'vidyutnidhi5',
    storageBucket: 'vidyutnidhi5.firebasestorage.app',
    iosBundleId: 'com.example.vidyut',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAuFr481cjL2WHsbsMeleXjKUyOAEyoUcg',
    appId: '1:940313957771:web:30b6f131a08a7a808a0b8e',
    messagingSenderId: '940313957771',
    projectId: 'vidyutnidhi5',
    authDomain: 'vidyutnidhi5.firebaseapp.com',
    storageBucket: 'vidyutnidhi5.firebasestorage.app',
    measurementId: 'G-0YXWN8HV32',
  );
}
