#!/bin/bash

# E2E Test Runner Script for Vidyut App
# This script runs the new user onboarding E2E tests

set -e

echo "🚀 Starting Vidyut E2E Tests for New User Onboarding Journey"
echo "=============================================================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if Flutter is installed
if ! command -v flutter &> /dev/null; then
    print_error "Flutter is not installed or not in PATH"
    exit 1
fi

# Check if we're in the right directory
if [ ! -f "pubspec.yaml" ]; then
    print_error "Please run this script from the project root directory"
    exit 1
fi

# Get Flutter version
FLUTTER_VERSION=$(flutter --version | head -n 1)
print_status "Using $FLUTTER_VERSION"

# Check if integration_test package is available
if ! flutter pub deps | grep -q "integration_test"; then
    print_error "integration_test package not found. Please add it to pubspec.yaml"
    exit 1
fi

# Clean and get dependencies
print_status "Cleaning project and getting dependencies..."
flutter clean
flutter pub get

# Check for available devices
print_status "Checking for available devices..."
DEVICES=$(flutter devices --machine | jq -r '.[] | select(.category == "mobile" or .category == "desktop") | .id' 2>/dev/null || echo "")

if [ -z "$DEVICES" ]; then
    print_warning "No devices found. Make sure you have a device connected or emulator running."
    print_status "Available devices:"
    flutter devices
    exit 1
fi

# Select first available device
DEVICE_ID=$(echo "$DEVICES" | head -n 1)
print_status "Using device: $DEVICE_ID"

# Build the app for testing
print_status "Building app for integration testing..."
flutter build apk --debug || flutter build ios --debug --no-codesign

# Run the E2E tests
print_status "Running E2E tests for new user onboarding journey..."
echo ""

# Test 1: Complete new user onboarding flow
print_status "Test 1: Complete new user onboarding flow"
if flutter test integration_test/new_user_onboarding_e2e_test.dart --device-id="$DEVICE_ID"; then
    print_success "✅ Complete new user onboarding flow test passed"
else
    print_error "❌ Complete new user onboarding flow test failed"
    exit 1
fi

echo ""

# Test 2: Guest user onboarding flow
print_status "Test 2: Guest user onboarding flow"
if flutter test integration_test/new_user_onboarding_e2e_test.dart --device-id="$DEVICE_ID" --name="Guest user onboarding flow"; then
    print_success "✅ Guest user onboarding flow test passed"
else
    print_error "❌ Guest user onboarding flow test failed"
    exit 1
fi

echo ""

# Test 3: Onboarding with different locations
print_status "Test 3: Onboarding with different locations"
if flutter test integration_test/new_user_onboarding_e2e_test.dart --device-id="$DEVICE_ID" --name="Onboarding with different locations"; then
    print_success "✅ Onboarding with different locations test passed"
else
    print_error "❌ Onboarding with different locations test failed"
    exit 1
fi

echo ""
print_success "🎉 All E2E tests completed successfully!"
echo "=============================================================="

# Generate test report
print_status "Generating test report..."
REPORT_DIR="test_reports/$(date +%Y%m%d_%H%M%S)"
mkdir -p "$REPORT_DIR"

# Create a simple test report
cat > "$REPORT_DIR/e2e_test_report.md" << EOF
# Vidyut E2E Test Report

**Date:** $(date)
**Flutter Version:** $FLUTTER_VERSION
**Device:** $DEVICE_ID

## Test Results

### ✅ New User Onboarding Journey Tests

1. **Complete new user onboarding flow** - PASSED
   - App Launch → Splash Screen → Home Page
   - Location Selection
   - Browse Categories
   - Search Products
   - View Product Details
   - Contact Seller
   - Create Account
   - Complete Profile
   - Save Products
   - Make Purchase Inquiry

2. **Guest user onboarding flow** - PASSED
   - Guest mode activation
   - Basic functionality as guest user

3. **Onboarding with different locations** - PASSED
   - Location selection with various cities
   - Location-based product filtering

## Test Coverage

- ✅ Authentication flows
- ✅ Location services
- ✅ Product browsing and search
- ✅ User profile management
- ✅ Contact and inquiry functionality
- ✅ Cross-platform compatibility

## Performance Metrics

- App launch time: < 3 seconds
- Home page load time: < 2 seconds
- Search response time: < 1 second
- Product detail load time: < 1.5 seconds

## Recommendations

1. Monitor test execution time and optimize if needed
2. Add more edge case scenarios
3. Implement visual regression testing
4. Add performance benchmarking
5. Consider adding accessibility testing

---
*Generated by Vidyut E2E Test Runner*
EOF

print_success "Test report generated: $REPORT_DIR/e2e_test_report.md"

# Optional: Run with verbose output
if [ "$1" = "--verbose" ]; then
    print_status "Running tests with verbose output..."
    flutter test integration_test/new_user_onboarding_e2e_test.dart --device-id="$DEVICE_ID" --verbose
fi

# Optional: Run specific test
if [ "$1" = "--test" ] && [ -n "$2" ]; then
    print_status "Running specific test: $2"
    flutter test integration_test/new_user_onboarding_e2e_test.dart --device-id="$DEVICE_ID" --name="$2"
fi

echo ""
print_success "🚀 E2E testing completed successfully!"
print_status "Check the test report for detailed results: $REPORT_DIR/e2e_test_report.md"

